### ISSUE TITLE
TAP reporter is broken in nodeunit@0.9.3+ (works in nodeunit 0.9.2)

### ISSUE THREAD

**Issue by iamstolis** [caolan/nodeunit#322]
tap dependency has been increased recently but the TAP reporter was not updated to reflect this change. It does not work. Try to run any test with `--reporter tap` option. You will get the following error
```
/somePath/node_modules/nodeunit/lib/reporters/tap.js:37
    var output = new TapProducer();
                  ^

TypeError: undefined is not a function
    at run (/somePath/node_modules/nodeunit/lib/reporters/tap.js:37:18)
    at Object.<anonymous> (/somePath/node_modules/nodeunit/bin/nodeunit:128:12)
    at Module._compile (module.js:541:32)
    at Object.<anonymous> (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function._load (module.js:409:3)
    at runMain (module.js:575:10)
    at run (node.js:361:7)
    at startup (node.js:153:9)
    at node.js:476:3
```

**Comment by mreinstein** [comment]
sorry, that's my bad. Should be fixed via https://github.com/caolan/nodeunit/commit/87fa1749f27b987f4c53c8e2ac6d3573914db867

published as 10.0.1

**Comment by iamstolis** [comment]
Thanks for a quick fix, but it would be ideal to release 0.9.4 with this fix as well. The packages that specify dependencies like nodeunit@~0.9.1 or nodeunit@0.9.x. remain broken because they download nodeunit@0.9.3 which contains this bug. Note that I am speaking about 3rd party package where I cannot upgrade the dependency to 0.10.1.

**Comment by mreinstein** [comment]
good idea. I'll push a 0.9.4 release now.

**Comment by iamstolis** [comment]
I have some more bad news. I have just tried your fix on 1.2.1 version of async package and it seems that it is not prefect sill. The output of 0.9.2 is
```
TAP version 13
# forever - async
ok 1 (unnamed assert)
ok 2 (unnamed assert)
# forever - sync
ok 3 (unnamed assert)
ok 4 (unnamed assert)
```
while the output of 0.10.1 is
```
forever - asyncTAP version 13
ok 1 - expect truthy value
ok 2 - expect truthy value
forever - syncok 3 - expect truthy value
ok 4 - expect truthy value
```
which is not correct.

**Comment by mreinstein** [comment]
any suggestions on how to fix this?

**Comment by iamstolis** [comment]
My guess is that there should be `tap.comment(name.toString());` instead of `process.stdout.write(name.toString());` in `testStart` but I am in a rush now. So, I cannot verify it. I can do it in few hours.

**Comment by mreinstein** [comment]
I think you're right. I've pulled down `async@1.2.1` and ran the tap reporter. here's my output:

```
TAP version 13
# forever - async
ok 1 - expect truthy value
ok 2 - expect truthy value
# forever - sync
ok 3 - expect truthy value
ok 4 - expect truthy value
# applyEach
ok 5 - expect truthy value
ok 6 - expect truthy value
ok 7 - expect truthy value
ok 8 - null passed instead of 'null'
ok 9 - expect truthy value
# applyEachSeries
ok 10 - expect truthy value
ok 11 - expect truthy value
ok 12 - expect truthy value
ok 13 - null passed instead of 'null'
ok 14 - expect truthy value
# applyEach partial application
ok 15 - expect truthy value
ok 16 - expect truthy value
ok 17 - expect truthy value
ok 18 - expect truthy value
# compose
ok 19 - expect truthy value
ok 20 - expect truthy value
ok 21 - expect truthy value
ok 22 - null passed instead of 'null'
ok 23 - expect truthy value
...
```

**Comment by mreinstein** [comment]
I just published `0.9.5` and `0.10.2` which should fix this. Great catch!

**Comment by iamstolis** [comment]
Thanks again for your quick response. I tried to use TAP reporter for tests of several packages affected by this issue (async, bcrypt, bunyan, grunt-bower-task, statsd, wrench). All of them run fine now (some of them ended up using 0.9.5, others 0.10.2).
